version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
      - keycloak

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "5000:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
